# Generated by Django 4.0.1 on 2022-05-15 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=100, verbose_name='название книги')),
                ('picture', models.ImageField(upload_to='books/%Y/%m/%d/', verbose_name='картинка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
                ('currency_price', models.CharField(max_length=4, verbose_name='валюта')),
                ('publishing_date', models.DateField(blank=True, verbose_name='Год издания')),
                ('pages', models.IntegerField(blank=True, verbose_name='количество страниц')),
                ('binding', models.CharField(blank=True, max_length=20, verbose_name='переплет')),
                ('format', models.CharField(blank=True, max_length=20, verbose_name='формат')),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN')),
                ('weigh', models.IntegerField(blank=True, verbose_name='вес')),
                ('age_restrictions', models.CharField(blank=True, max_length=20, verbose_name='возрастные ограничения')),
                ('value_available', models.IntegerField(blank=True, verbose_name='количество в наличии')),
                ('available', models.BooleanField(default=None, verbose_name='доступен для заказа')),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения в каталог')),
                ('publication_edit_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения карточки')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='book_authors', to='directories.author')),
                ('editor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='book_editors', to='directories.editor')),
                ('genre', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='book_genres', to='directories.genre')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_series', to='directories.serie')),
            ],
        ),
    ]
