# Generated by Django 4.0.1 on 2022-06-26 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0001_initial'),
        ('books', '0004_alter_book_age_restrictions_alter_book_pages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='serie',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='book_series', to='directories.serie'),
        ),
    ]
