# Generated by Django 4.0.1 on 2022-06-30 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='age_restrictions',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='возрастные ограничения'),
        ),
    ]
