# Generated by Django 4.0.1 on 2022-06-30 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_age_restrictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='age_restrictions',
            field=models.CharField(blank=True, max_length=20, verbose_name='возрастные ограничения'),
        ),
        migrations.AlterField(
            model_name='book',
            name='value_available',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='количество в наличии'),
        ),
    ]
