# Generated by Django 4.0.1 on 2022-06-30 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_value_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='value_available',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='количество в наличии'),
        ),
    ]
