# Generated by Django 4.0.1 on 2022-03-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_bookincart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookincart',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='цена'),
        ),
    ]
