# Generated by Django 4.0.1 on 2022-06-22 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_available'),
        ('carts', '0002_alter_bookincart_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookincart',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books_in_cart', to='books.book', verbose_name='Книга'),
        ),
    ]
