# Generated by Django 4.0.1 on 2022-07-02 13:18

import carts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_alter_bookincart_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookincart',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(carts.models.BookInCart.max_quantity)], verbose_name='количество'),
        ),
    ]
