# Generated by Django 4.0.1 on 2022-01-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_number', models.IntegerField(verbose_name='Номер квартиры')),
                ('level', models.IntegerField(verbose_name='Этаж')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Продана')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения в базу данных')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего редактирования в БД')),
            ],
        ),
    ]
