# Generated by Django 4.0.1 on 2022-01-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='lux',
            field=models.BooleanField(default=False, verbose_name='Люкс'),
        ),
    ]
