# Generated by Django 4.0.1 on 2022-01-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0002_flat_lux'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flat',
            options={'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.AddField(
            model_name='flat',
            name='square',
            field=models.IntegerField(default=70, verbose_name='Площадь квартиры'),
            preserve_default=False,
        ),
    ]
