# Generated by Django 4.0.1 on 2022-01-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0003_alter_flat_options_flat_square'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquareDim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dim', models.CharField(max_length=100, verbose_name='единица измерения площади')),
            ],
            options={
                'verbose_name': 'единица измерения',
                'verbose_name_plural': 'единицы измерений',
            },
        ),
    ]
