# Generated by Django 4.0.1 on 2022-01-23 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': ('Автор',), 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='editor',
            options={'verbose_name': ('Издательство',), 'verbose_name_plural': 'Издательства'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': ('Жанр',), 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='serie',
            options={'verbose_name': ('Серия',), 'verbose_name_plural': 'Серии'},
        ),
    ]
