# Generated by Django 4.0.1 on 2022-05-15 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(blank=True, default='новый', max_length=20, null=True, verbose_name='статус заказа')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_info', models.TextField(blank=True, verbose_name='контактная информация')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='обновлен')),
                ('tel', models.CharField(default='+375XX XXX XX XX', max_length=20, verbose_name='телефон')),
                ('email_adress', models.EmailField(max_length=254, null=True, verbose_name='email')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carts.cart', verbose_name='заказ')),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderstatus', to='orders.orderstatus', verbose_name='статус заказа')),
            ],
        ),
    ]
