# Generated by Django 4.0.1 on 2022-03-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderstatus_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='order_status',
            field=models.CharField(blank=True, default='новый', max_length=20, null=True, verbose_name='статус заказа'),
        ),
    ]
