# Generated by Django 4.0.1 on 2022-04-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderstatus_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_info',
            field=models.TextField(blank=True, verbose_name='контактная информация'),
        ),
    ]
