# Generated by Django 4.0.1 on 2022-05-01 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_adress_profile_city_profile_country_and_more'),
        ('orders', '0005_alter_order_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.profile', verbose_name='телефон'),
        ),
    ]
