# Generated by Django 4.0.1 on 2022-05-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tel',
            field=models.CharField(default='+375XX XXX XX XX', max_length=20, verbose_name='телефон'),
        ),
    ]
