# Generated by Django 4.0.1 on 2022-05-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_info',
            field=models.TextField(blank=True, verbose_name='контактная информация'),
        ),
    ]
