# Generated by Django 4.0.1 on 2022-05-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_adress',
            field=models.EmailField(max_length=254, null=True, verbose_name='email'),
        ),
    ]
